### ISSUE TITLE
Install inconsolata package on gitrunner

### ISSUE THREAD

**Issue by fangohr** [oscovida/oscovida#207]
<img width="1650" alt="Screenshot 2021-01-25 at 08 55 53" src="https://user-images.githubusercontent.com/4489119/105676705-31c12880-5eeb-11eb-840d-6bc897375bd9.png">

Just so it is not forgotten ;)

**Comment by RobertRosca** [comment]
Ah yes, I fixed this after moving to the self-hosted runner on our new server, but forgot to mount the overlay which which contained the change to the container when starting it up as an instance.

Did that now and I've triggered the page generation manually.

**Comment by fangohr** [comment]
The warning message is still present though (see for example https://oscovida.github.io/html/Brazil.html).

**Comment by RobertRosca** [comment]
Hmmm that is odd, it worked when I ran it manually after mounting the overlay, the environments seem to be even more well isolated than I intended...

**Comment by RobertRosca** [comment]
Ah yes I figured it out in the meantime, the font was correctly installed but there was a matplotlib font caching issue, where the cache had to be updated for matplotlib to detect the font.

After installing the font in an overlay I changed which directories got mounted in for permanent storage, and started re-using an old cache from before installing the font.

**Comment by RobertRosca** [comment]
Has been fixed now!
